### ISSUE TITLE
Design matrix for interaction term missing factor when no intercept is used

### ISSUE THREAD

**Issue by filthysocks** [bambinos/formulae#114]
Hello,

I'm using a model without intercept with an interaction term between two groups and i think i'm missing an interaction term.

Here a simple example that reproduces the problem:
```
from formulae import design_matrices
import pandas as pd

user = ["1","1","2","2","3","3"]
group = ["a","b"]*3
score = [1]*len(user)

data = pd.DataFrame({"user":user, "group":group, "score":score})

dm = design_matrices("score ~ 0 + user*group",data)
dm.common
```

output:
```
CommonEffectsMatrix with shape (6, 6)
Terms:  
  user  
    kind: categoric
    levels: ['1', '2', '3']
    columns: 0:3
  group  
    kind: categoric
    levels: ['b']
    column: 3
  user:group  
    kind: interaction
    levels: ['2, b', '3, b']
    columns: 4:6
```

Where is the interaction term '1, b'?
Is this a bug or am i not getting something here?

Version: 0.5.4
